version: '3'

services:
  nodejs:
    image: myblog-api:3.3
    container_name: nodejs
    build: 
      context: ./
      dockerfile: ./server/docker/Dockerfile
    restart: unless-stopped
    ports:
      - "6060:6060"
      - "2208:22"
    environment:
      NODE_ENV: production  #development
    
    networks:
      - app-network
      
  webserver:
    image: myblog:2.3
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - nodejs
    networks:
      - app-network
  
  mysql:
    image: mysql-sql:1.3
    container_name: mysql
    build: 
      context: ./
      dockerfile: ./server/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=root   #创建test用户
      - MYSQL_PASSWORD=123456 #设置test用户的密码
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
