version: '3'

services:
  nodejs:
    image: myblog-api:1.6
    container_name: nodejs
    restart: unless-stopped
    environment: 
      - NODE_ENV=production
    ports:
      - "6060:6060"
    networks:
      - app-network
      
  webserver:
    image: myblog:1.9
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - nodejs
    networks:
      - app-network
  
  db:
    image: mysql:5.7.24
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=root   #创建test用户
      - MYSQL_PASSWORD=123456 #设置test用户的密码
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network

networks:
  app-network:
    driver: bridge